<font color='red'/>BootCamp 4th week -numpy- 20/04/2024 - 4:00 - 7:00 pm

In [4]:
import numpy as np

mylist = [1,2,3,4,5]
print(type(mylist))
print(mylist)
np_arr = np.array(mylist)
print(type(np_arr))
print(np_arr)

<class 'list'>
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [14]:
import time as time
size = 1000000 
l1 = range(size) # 0, 1, 2...... 
l2 = range(size) # 0, 1, 2 
ar1 = np.arange(size)
print(ar1)
ar2 = np.arange(size)
print(ar2)
start1 = time.time() 
result2 = ar1+ar2 
stop1 = time.time() 
start2 = time.time() 
result3 = l1,l2
stop2 = time.time()
print("time taken numpy: ", (stop1-start1)*1000, 'ms')
print("time taken list: ", (stop2-start2)*1000, 'ms')

[     0      1      2 ... 999997 999998 999999]
[     0      1      2 ... 999997 999998 999999]
time taken numpy:  6.949186325073242 ms
time taken list:  0.0 ms


In [17]:
my_list = [[[1,2,3],
            [4,5,6],
            [7,8,9]]]
c = np.array(my_list)

In [19]:
c.shape


(1, 3, 3)

In [20]:
c.ndim

3

In [21]:
c


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
c[0][1][2]

6

In [23]:
c[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [24]:
c


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
c[0,1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
c[0,1,:]

array([4, 5, 6])

In [27]:
c[0,1,2]

6

In [28]:
c[0,2,2]

9

In [29]:
##Statistical operations

In [30]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype='float')
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [31]:
print('mean',arr1.mean())
print('max',arr1.max())
print('min',arr1.min())
print('sum',arr1.sum())


mean 6.5
max 12.0
min 1.0
sum 78.0


In [33]:
print('column wise min',np.amin(arr1,axis=0))
print('row wise min',np.amin(arr1,axis=1))

print('clumn wise max',np.amax(arr1,axis=0))
print('row wise max',np.amax(arr1,axis=1))
      
print('clumn wise sum',np.sum(arr1,axis=0))
print('row wise sum',np.sum(arr1,axis=1))

column wise min [1. 2. 3. 4.]
row wise min [1. 5. 9.]
clumn wise max [ 9. 10. 11. 12.]
row wise max [ 4.  8. 12.]
clumn wise sum [15. 18. 21. 24.]
row wise sum [10. 26. 42.]


In [34]:
dist = [180,170,135,191,250]
time= [7,6,8,9,13]

d_arr = np.array(dist)
t_arr = np.array(time)

s_arr = d_arr/t_arr

In [35]:
s_arr

array([25.71428571, 28.33333333, 16.875     , 21.22222222, 19.23076923])

In [39]:
# filtering an  array
s_arr[s_arr >20]

array([25.71428571, 28.33333333, 21.22222222])

In [43]:
arr_2 = np.array([1,2,3,4,5,6,7,8,9])
arr_2


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr_2.shape

(9,)

In [46]:
new_arr_2 = arr_2.reshape(3,3) ## 9 elements possiblities 3*3
new_arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
new_arr_2 = arr_2.reshape(3,4) ## 9 elements possiblities 3*3
new_arr_2

ValueError: cannot reshape array of size 9 into shape (3,4)

In [48]:
new_arr_2 = arr_2.reshape(1,3) ## 9 elements possiblities 3*3
new_arr_2

ValueError: cannot reshape array of size 9 into shape (1,3)

In [49]:
new_arr_2 = arr_2.reshape(1,9) ## 9 elements possiblities 3*3
new_arr_2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
new_arr_2.T ## transpose to reverse the 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [52]:
new_arr_2 = arr_2.reshape(3,3) ## 9 elements possiblities 3*3
new_arr_2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
new_arr_2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
np.sin(np.pi/2)

1.0

In [55]:
np.cos(np.pi)

-1.0

## NUMPY Practice 

In [2]:
import numpy as np
narr = np.array( [1.0, 2, 3.5, 0.2, True] )
narr
print(type(narr))

<class 'numpy.ndarray'>


In [3]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[:3])

[1, 2, 3]


In [4]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[2:-3])

[3, 5, 4, 6, 7, 8]


In [6]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[ : : -2])
print(array_1[ 1: : 2])

[2, 5, 7, 4, 3, 1]
[2, 5, 6, 8, 3]


In [20]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
import numpy as np
numpy_arr = np.array(array_1)
print(numpy_arr)
m =2
n=6
result = numpy_arr[(numpy_arr > m) & (numpy_arr < n)]
print(result)

[1 2 3 5 4 6 7 8 5 3 2]
[3 5 4 5 3]


In [2]:
import numpy as np
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros((5,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
np.arange(5) ## range of 5

array([0, 1, 2, 3, 4])

In [7]:
np.arange(3,35,4) ## starting point and exclude end point and steps increase

array([ 3,  7, 11, 15, 19, 23, 27, 31])

In [8]:
# random generator its inbuilt in numpy 
np.random.randint(1,4,size=10) ## it has lower and upper bound and size of the random numbers

array([1, 1, 2, 1, 2, 2, 3, 2, 2, 2])

In [9]:
#if not given lower bound we can use only upper and lets see the resut
np.random.randint(4,size=10)

array([0, 1, 3, 2, 2, 2, 1, 0, 2, 1])

In [12]:
np.random.randint(1,size=10) ## it will take atleaset one argument and >0 should be required

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
import numpy as np
array_multipleof5 = np.arange(5,55,5)

print(array_multipleof5)

[ 5 10 15 20 25 30 35 40 45 50]


In [1]:
n = 4

import numpy as np

# Create an 'n*n' array of all ones
arr1 =np.ones((n,n),dtype='int')


# Fill the array with zeroes from second index (i.e. index 1) to second last index.
arr1[1:n-1,1:n-1]=0 # its working to fill with zeros except boarders
print(arr1)
# Do this for both row indices and column indices
##np.full((arr1[1:n-1,1:n-1]),0,dtype='int') - not working
# Print the array created

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [22]:

#np.full(): It is used to create a constant array of any number ‘n’.
#np.tile(): It is used to create a new array by repeating an existing array for a particular number of times.
#np.eye(): It is used to create an identity matrix of any dimension

help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible wit

hstack: It puts two arrays with the same number of rows together. By using this command, the number of rows stays the same, while the number of columns increases. 
vstack: It puts two arrays on top of each other. This command works only when the number of columns in both the arrays is the same. This command can only change the number rows of an array. 
reshape: It can change the shape of an array as long as the number of elements in the array before and after the reshape operation is the same. 

In [49]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a = a.reshape(2,3)
a2 = np.array([10,11,12,13,14,15])
a2 = a2.reshape(2,3)
np.vstack((a,a2))
np.hstack((a,a2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

In [58]:
#Consider an (11,12) shape array. What is the index (x,y) of the 100th element?
#Note: For counting the elements, go row-wise. For example, in the array:
import numpy as np
arr = np.arange(132)
n=100
#print(arr)
arr = arr.reshape(11,12)
print(arr)
print(np.shape(arr))
# Flatten the array
arr_flattened = arr.ravel()
print(arr_flattened)
# Find the indices of the nth element
indices = np.unravel_index(n-1, np.shape(arr))
print(indices)

##Upgrade solution
#You can create an 11 x 12 array using np.array(range(1, 11*12+1)). You can reshape it to an (11 x 12) array and then check the position of 100. Be clear that the indexing starts from 0; hence, the 9th row will have the index 8.
#Alternatively, you can also use np.unravel_index(99, (11,12)) on the created array.

.

[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131]]
(11, 12)
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105

In [55]:
arr12 = np.hstack(arr)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131])

In [59]:
import numpy as np
p = [[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p,-1)
##reshape() function returns a 1-D array when you specify the shape as -1.

array([1, 5, 3, 7, 4, 9])

In [78]:
import numpy as np

p = [[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]]
array_1= np.array(p)
# alterative way to find solution
#print(array_1[array_1%2 != 0].reshape(5, 2))

[ 1  3  5  7  9 11 13 15 17 19]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [68]:
p1 = np.reshape(p,-1)
p1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
p2 =p1[: : 2]
p2.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [79]:
p = [[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [27]:
import numpy as np

arr1 = [[7, 13, 14],

[18, 10, 17],

[11, 12, 19]]

arr2 = [16, 6, 1]
arr3 = np.array([[5, 8, 4, 3]])
arr3_1 = arr3.T
arr4 = np.vstack((arr1,arr2))
arr4

array([[ 7, 13, 14],
       [18, 10, 17],
       [11, 12, 19],
       [16,  6,  1]])

In [29]:
arr_flattened = arr4.ravel()

#print(arr4)
print(arr3_1)
arr5 = np.concatenate((arr4, arr3_1),axis=1)
print(arr5)
#np.transpose(arr5)
#arr5.reshape(4,4)

[[5]
 [8]
 [4]
 [3]]
[[ 7 13 14  5]
 [18 10 17  8]
 [11 12 19  4]
 [16  6  1  3]]


In [2]:
#What will the output of np.eye(2, dtype = int).reshape(4, 1).T be?
import numpy as np
np.eye(2, dtype = int).reshape(4, 1).T

array([[1, 0, 0, 1]])

In [3]:
import numpy as np
a = np.arange(10)
f = np.vectorize(lambda x: x+1)
f(a)

#np.arange(10) returns the array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]. 
#The lambda function then adds one to every element when applied to the array. Hence, the final output becomes:
#[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.full((2,2), 1) == np.ones((2,2))

array([[ True,  True],
       [ True,  True]])

In [5]:
import numpy as np
a = np.array( [7, 10, 2, 4, 13, 16])
med = np.percentile(a, 50)
print(med)

8.5


In [8]:
in_list = [[9,8,7],[6,5,4],[3,2,1]]
import numpy as np
np_arr1 = np.array(in_list)
np_arr1[np_arr1[: :]>3]

array([9, 8, 7, 6, 5, 4])

In [11]:
import numpy as np
input = [11,22,33,44,55,66,77]
np_in = np.array(input)
percentile_60 = np.percentile(np_in, 60)
percentile_60_rounded = round(percentile_60, 2)
print(percentile_60_rounded)

50.6


In [14]:
import statistics

def calculate_stats(n):
    numbers = list(range(n))
    numbers1 = list(range(n-1))
    mean = round(statistics.mean(numbers), 2)
    variance = round(statistics.variance(numbers1), 2)
    std_dev = round(statistics.stdev(numbers), 2)
    return mean, variance, std_dev

# Example usage
n = 16
mean, variance, std_dev = calculate_stats(n)
print(f"Mean: {mean}, Variance: {variance}, Standard Deviation: {std_dev}")


Mean: 7.5, Variance: 20, Standard Deviation: 4.76


In [17]:
import numpy as np

def calculate_mean(n):
    numbers = np.arange(n)
    mean = np.mean(numbers)
    return round(mean, 2)

# Example usage
n = 16
mean = calculate_mean(n)
print(mean)

7.5


In [19]:
import numpy as np

def calculate_std_dev(n):
    numbers = np.arange(n)
    std_dev = np.std(numbers)
    return round(std_dev, 2)

# Example usage
n = 16
std_dev = calculate_std_dev(n)
print(f"Standard deviation of numbers from 0 to {n-1}: {std_dev}")

Standard deviation of numbers from 0 to 15: 4.61


In [21]:
import numpy as np

def calculate_variance(n):
    numbers = np.arange(n)
    variance = np.var(numbers)
    return round(variance, 2)

# Example usage
n = 16
variance = calculate_variance(n)
print(f"Variance of numbers from 0 to {n-1}: {variance}")

Variance of numbers from 0 to 15: 21.25


In [46]:
import numpy as np
n=5
arr = np.zeros((n, n), dtype=int)
# Fill ones in the shape of Z
#print(np.arange(n-1 ))
arr[0, :] = 1  # Top row
arr[-1, :] = 1  # Bottom row
#arr[np.arange(1, n-1), np.arange(1, n-1)] = 1  # Diagonal    
#arr[np.arange(1,n-2), np.arange( 1,n-1)] = 1 
arr[np.arange(n), np.arange(n-1, -1, -1)] = 1
print(arr)

[[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 1 1 1 1]]


In [38]:
import numpy as np

# Sample 2D NumPy array
array = np.array([[3, 2, 5],
                  [1, 4, 7],
                  [2, 3, 6],
                  [3, 1, 4]])

# Sort the array by the 1st column, and then by subsequent columns if there are ties
sorted_indices = np.lexsort((array[:, 1], array[:, 0]))

# Use the sorted indices to rearrange the array
sorted_array = array[sorted_indices]

print(sorted_array)


[[1 4 7]
 [2 3 6]
 [3 1 4]
 [3 2 5]]


In [2]:
p=[[1, 5],
 [3, 7],
 [4, 9]]
np.reshape(p, -1)

array([1, 5, 3, 7, 4, 9])

In [7]:
import numpy as np
array_1 = [[1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]
 [11, 12, 13, 14, 15]
 [16, 17, 18, 19, 20]]

print(array_1[array_1%2 != 0])

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8256\3464478231.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1 = [[1, 2, 3, 4, 5]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8256\3464478231.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1 = [[1, 2, 3, 4, 5]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8256\3464478231.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1 = [[1, 2, 3, 4, 5]
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8256\3464478231.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1 = [[1, 2, 3, 4, 5]
C:\Users\ADMIN\AppData\Local\Temp\ipyk

TypeError: list indices must be integers or slices, not tuple