In [ ]:
# !pip install numpy -- required only when numpy is not installed

In [1]:
# import numpy 

import numpy as np

In [2]:
# create an ND array from python list

mylist = [1,2,3,4,5]

In [3]:
type(mylist)

list

In [4]:
# np.array() : which will convert given object into an array

my_arr = np.array(mylist)

In [5]:
print(my_arr)

[1 2 3 4 5]


In [6]:
type(my_arr)

numpy.ndarray

In [7]:
print(mylist)
print(my_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [47]:
list(my_arr)

[1, 2, 3, 4, 5]

In [ ]:
# mylist is python list which does not support much scientific cal
# my_arr is vector nd array which supprorts many math / sci  cal

In [ ]:
# just for demo purpose / no need of attempting this lab

In [9]:
import cv2

In [10]:
pic = cv2.imread('sample_img.jpeg')

In [11]:
pic

array([[[158, 138,  53],
        [159, 139,  54],
        [159, 139,  54],
        ...,
        [125,  67,  62],
        [128,  71,  62],
        [136,  79,  70]],

       [[159, 139,  54],
        [159, 139,  54],
        [160, 140,  55],
        ...,
        [114,  58,  53],
        [115,  60,  53],
        [122,  67,  60]],

       [[160, 139,  57],
        [161, 140,  58],
        [161, 140,  58],
        ...,
        [105,  50,  47],
        [103,  49,  42],
        [111,  57,  50]],

       ...,

       [[ 85,  79, 120],
        [ 84,  78, 119],
        [ 83,  77, 118],
        ...,
        [ 66,  70, 129],
        [ 68,  72, 131],
        [ 68,  72, 131]],

       [[ 98,  88, 124],
        [ 98,  88, 124],
        [ 97,  87, 123],
        ...,
        [ 65,  68, 129],
        [ 66,  69, 130],
        [ 66,  69, 130]],

       [[108,  94, 128],
        [108,  94, 128],
        [106,  92, 126],
        ...,
        [ 66,  67, 128],
        [ 66,  67, 128],
        [ 66,  67, 128]]

In [12]:
type(pic)

numpy.ndarray

In [77]:
pic.shape

(151, 270, 3)

# Numpy vs Python

In [13]:
# speed # storage

In [14]:
# how much memory is consumed by single digit
num = 4

In [15]:
import sys

In [16]:
sys.getsizeof(num) , ' bytes'

(28, ' bytes')

In [17]:
# for 1000 intigers i need 28000 bytes

In [18]:
my_arr

array([1, 2, 3, 4, 5])

In [19]:
# itemsize : return size of single element in given array

In [20]:
my_arr.itemsize, ' bytes'

(8, ' bytes')

In [ ]:
# for 1000 integers i am saving 20000

In [22]:
len(mylist)*28, ' bytes'

(140, ' bytes')

In [23]:
my_arr.nbytes, ' bytes'

(40, ' bytes')

In [24]:
len(mylist)

5

In [41]:
import time

In [42]:
time.time()

1713613189.312278

In [43]:
size = 1000000

l1 = range(size) # 0, 1, 2......
l2 = range(size) # 0, 1, 2

ar1 = np.arange(size)
ar2 = np.arange(size)

start = time.time()
result1 = [x+y  for x,y in zip(l1,l2)]
stop = time.time()
print("time taken : ", (stop-start)*1000, 'ms')


time taken :  299.64399337768555 ms


In [44]:
size = 1000000

l1 = range(size) # 0, 1, 2......
l2 = range(size) # 0, 1, 2

ar1 = np.arange(size)
ar2 = np.arange(size)

start1 = time.time()
result2 = ar1+ar2
stop1 = time.time()

print("time taken : ", (stop-start)*1000, 'ms')

time taken :  299.64399337768555 ms


In [46]:
result2

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

# Numpy

In [ ]:
# creating 1D array

In [48]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [61]:
a[2]

3

In [49]:
# creating 2D array

In [50]:
mylist = [[1,2,3],[4,5,6]]
b = np.array(mylist)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
b[1][1]

5

In [52]:
# shape : returns rows and columns

b.shape

(2, 3)

In [53]:
# ndim : returns number of dimentions 
a.ndim

1

In [54]:
b.ndim

2

In [55]:
# create 3 dimentional array

In [60]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
mylist1 = [
    [[1,2,3],[4,5,6]],
    [[8,9,10],[11,12,13]]
]

c = np.array(mylist1)

In [83]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [58]:
c.shape

(2, 2, 3)

In [59]:
c.ndim

3

In [68]:
c[1][0][2]

10

In [69]:
# slicing

In [70]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
b[1 , 1:]

array([5, 6])

In [73]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [74]:
c[1,:2]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [75]:
c[1,:]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [84]:
# statistical operations

In [85]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]],dtype = 'float')
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [86]:
print("mean value is : ", arr1.mean())
print("max value is : ", arr1.max())
print("min value is : ", arr1.min())
print("Total value is : ", arr1.sum())

mean value is :  6.5
max value is :  12.0
min value is :  1.0
Total value is :  78.0


In [87]:
print("Column wise summation is : ", np.sum(arr1, axis = 0))

Column wise summation is :  [15. 18. 21. 24.]


In [88]:
print("row wise summation is : ", np.sum(arr1, axis = 1))

row wise summation is :  [10. 26. 42.]


In [89]:
print("Column wise minimum is : ", np.amin(arr1, axis = 0))
print("row wise minimum is : ", np.amin(arr1, axis = 1))

Column wise minimum is :  [1. 2. 3. 4.]
row wise minimum is :  [1. 5. 9.]


In [91]:
x = np.array([[1,2],[3,4]])
y = np.array([[2,3],[4,5]])

In [94]:
x+y

array([[3, 5],
       [7, 9]])

In [95]:
x*y

array([[ 2,  6],
       [12, 20]])

In [96]:
x/y

array([[0.5       , 0.66666667],
       [0.75      , 0.8       ]])

In [99]:
dist = [180,170,135,191,250]
time = [6,7,10,13,11]

d_arr = np.array(dist)
t_arr = np.array(time)

s_arr = d_arr/t_arr


In [98]:
s_arr

array([30.        , 24.28571429, 13.5       , 14.69230769, 22.72727273])

In [100]:
# filtering an array

In [102]:
s_arr[s_arr<20]

array([13.5       , 14.69230769])

In [103]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [104]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
# convert single dimentional array to mutli dimentional array

# reshape

In [106]:
arr_1.shape

(12,)

In [107]:
new_arr = arr_1.reshape(3,4)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [108]:
new_arr.shape

(3, 4)

In [109]:
new_arr.ndim

2

In [110]:
new_arr1 = arr_1.reshape(3,5)
new_arr1

ValueError: cannot reshape array of size 12 into shape (3,5)

In [111]:
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
new_arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [113]:
# trigo

In [114]:
np.sin(np.pi/2)

1.0

In [115]:
np.cos(np.pi/2)

6.123233995736766e-17

In [116]:
np.cos(np.pi)

-1.0

## <font color='red'> Pandas Boot Camp 21/04/2024 6:00 to 9:00 pm

### Pandas is goig to work for Data Cleaning, Data Manupulation,Data Analysis

### Pandas Data Structures 
      --> Series - it is used to store ,process or analyse 1D data
      --> Data Frame -it is used to store ,process or analyse 2D data Ex. excel data
      Multiple set series combined to structure called Data Frame
      Pandas Vs Numpy (DataFrame vs arrays )(Pandas are built ontop of numpy)
      Numpy - mathematically algebra,trigano meter, matrix
      Pandas - Data(rows/coloumns), clean data,manipulate data
      Sql operations using pandas(elastic search,mango etc)

In [2]:
import pandas as pd
nums = [3,6,1,7,9]
nums_series = pd.Series(nums)
nums_series

0    3
1    6
2    1
3    7
4    9
dtype: int64

In [3]:
type(nums_series)

pandas.core.series.Series

In [5]:
print('Max number is :',nums_series.max())
print('Min number is :',nums_series.min())
print('Average number is :',nums_series.mean())
print('Standard deviation number is :',nums_series.std())
print('Median number is :',nums_series.median())
print('Nums values are  :',nums_series.values)

Max number is : 9
Min number is : 1
Average number is : 5.2
Standard deviation number is : 3.1937438845342623
Median number is : 6.0
Nums values are  : [3 6 1 7 9]


In [6]:
s1 = pd.Series([1,2],index=['a','b'],name='s1')
s2 = pd.Series([3,4],index=['a','b'],name='s2')

# concat = combine multiple series to form dataframe
new_df = pd.concat([s1,s2],axis=1) #colmn wise - axis=1(horizantal) , row wise axis=0
new_df


s1  s2
a   1   3
b   2   4

In [7]:
new_df = pd.concat([s1,s2],axis=0) #colmn wise - axis=1 , row wise axis=0(vertical)
new_df

a    1
b    2
a    3
b    4
dtype: int64

In [8]:
new_df = pd.concat([s1,s2]) #colmn wise - axis=1 , row wise axis=0  default vertical(axis=0)
new_df

a    1
b    2
a    3
b    4
dtype: int64

In [9]:
# concat = combine multiple series to form dataframe
new_df = pd.concat([s1,s2],axis=1) #colmn wise - axis=1(horizantal) , row wise axis=0
new_df

s1  s2
a   1   3
b   2   4

In [10]:
# data loading
#pd.read_csv("path odf file")
df = pd.read_csv("telecom_churn.csv")
df

State  Account length  Area code International plan Voice mail plan  \
0       KS             128        415                 No             Yes   
1       OH             107        415                 No             Yes   
2       NJ             137        415                 No              No   
3       OH              84        408                Yes              No   
4       OK              75        415                Yes              No   
...    ...             ...        ...                ...             ...   
3328    AZ             192        415                 No             Yes   
3329    WV              68        415                 No              No   
3330    RI              28        510                 No              No   
3331    CT             184        510                Yes              No   
3332    TN              74        415                 No             Yes   

      Number vmail messages  Total day minutes  Total day calls  \
0                        25              265.1              110   
1                        26              161.6              123   
2                         0              243.4              114   
3                         0              299.4               71   
4                         0              166.7              113   
...                     ...                ...              ...   
3328                     36              156.2               77   
3329                      0              231.1               57   
3330                      0              180.8              109   
3331                      0              213.8              105   
3332                     25              234.4              113   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0                45.07              197.4               99             16.78   
1                27.47              195.5              103             16.62   
2                41.38              121.2              110             10.30   
3                50.90               61.9               88              5.26   
4                28.34              148.3              122             12.61   
...                ...                ...              ...               ...   
3328             26.55              215.5              126             18.32   
3329             39.29              153.4               55             13.04   
3330             30.74              288.8               58             24.55   
3331             36.35              159.6               84             13.57   
3332             39.85              265.9               82             22.60   

      Total night minutes  Total night calls  Total night charge  \
0                   244.7                 91               11.01   
1                   254.4                103               11.45   
2                   162.6                104                7.32   
3                   196.9                 89                8.86   
4                   186.9                121                8.41   
...                   ...                ...                 ...   
3328                279.1                 83               12.56   
3329                191.3                123                8.61   
3330                191.9                 91                8.64   
3331                139.2                137                6.26   
3332                241.4                 77               10.86   

      Total intl minutes  Total intl calls  Total intl charge  \
0                   10.0                 3               2.70   
1                   13.7                 3               3.70   
2                   12.2                 5               3.29   
3                    6.6                 7               1.78   
4                   10.1                 3               2.73   
...                  ...               ...                ...   
3328                 9.9                 6            

In [11]:
# .head() : display first 5 rows from the data
df.head()

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False

In [12]:
#df.head(n) : display n rows from the data
df.head(2)

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3                2.7   
1                13.7                 3                3.7   

   Customer service calls  Churn  
0                       1  False  
1                       1  False

In [13]:
# .tail() : display last 5 rows from the data
# .tail(n) : display last n rows from the data
df.tail(3)

State  Account length  Area code International plan Voice mail plan  \
3330    RI              28        510                 No              No   
3331    CT             184        510                Yes              No   
3332    TN              74        415                 No             Yes   

      Number vmail messages  Total day minutes  Total day calls  \
3330                      0              180.8              109   
3331                      0              213.8              105   
3332                     25              234.4              113   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
3330             30.74              288.8               58             24.55   
3331             36.35              159.6               84             13.57   
3332             39.85              265.9               82             22.60   

      Total night minutes  Total night calls  Total night charge  \
3330                191.9                 91                8.64   
3331                139.2                137                6.26   
3332                241.4                 77               10.86   

      Total intl minutes  Total intl calls  Total intl charge  \
3330                14.1                 6               3.81   
3331                 5.0                10               1.35   
3332                13.7                 4               3.70   

      Customer service calls  Churn  
3330                       2  False  
3331                       2  False  
3332                       0  False

In [14]:
# .shape : number of rows and colums
df.shape

(3333, 20)

In [15]:
#.size : number of data points present in data(row*columns)
df.size

66660

In [16]:
# .columns : gives a list of columnsin the data
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')

In [17]:
df.columns.to_list()

['State',
 'Account length',
 'Area code',
 'International plan',
 'Voice mail plan',
 'Number vmail messages',
 'Total day minutes',
 'Total day calls',
 'Total day charge',
 'Total eve minutes',
 'Total eve calls',
 'Total eve charge',
 'Total night minutes',
 'Total night calls',
 'Total night charge',
 'Total intl minutes',
 'Total intl calls',
 'Total intl charge',
 'Customer service calls',
 'Churn']

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   State                   3333 non-null   object 
 1   Account length          3333 non-null   int64  
 2   Area code               3333 non-null   int64  
 3   International plan      3333 non-null   object 
 4   Voice mail plan         3333 non-null   object 
 5   Number vmail messages   3333 non-null   int64  
 6   Total day minutes       3333 non-null   float64
 7   Total day calls         3333 non-null   int64  
 8   Total day charge        3333 non-null   float64
 9   Total eve minutes       3333 non-null   float64
 10  Total eve calls         3333 non-null   int64  
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3333 non-null   int64  
 14  Total night charge      3333 non-null   

In [19]:
# in pandas 'MH' = object very similar to string in python

df.isnull()

State  Account length  Area code  International plan  Voice mail plan  \
0     False           False      False               False            False   
1     False           False      False               False            False   
2     False           False      False               False            False   
3     False           False      False               False            False   
4     False           False      False               False            False   
...     ...             ...        ...                 ...              ...   
3328  False           False      False               False            False   
3329  False           False      False               False            False   
3330  False           False      False               False            False   
3331  False           False      False               False            False   
3332  False           False      False               False            False   

      Number vmail messages  Total day minutes  Total day calls  \
0                     False              False            False   
1                     False              False            False   
2                     False              False            False   
3                     False              False            False   
4                     False              False            False   
...                     ...                ...              ...   
3328                  False              False            False   
3329                  False              False            False   
3330                  False              False            False   
3331                  False              False            False   
3332                  False              False            False   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0                False              False            False             False   
1                False              False            False             False   
2                False              False            False             False   
3                False              False            False             False   
4                False              False            False             False   
...                ...                ...              ...               ...   
3328             False              False            False             False   
3329             False              False            False             False   
3330             False              False            False             False   
3331             False              False            False             False   
3332             False              False            False             False   

      Total night minutes  Total night calls  Total night charge  \
0                   False              False               False   
1                   False              False               False   
2                   False              False               False   
3                   False              False               False   
4                   False              False               False   
...                   ...                ...                 ...   
3328                False              False               False   
3329                False              False               False   
3330                False              False               False   
3331                False              False               False   
3332                False              False               False   

      Total intl minutes  Total intl calls  Total intl charge  \
0                  False             False              False   
1                  False             False              False   
2                  False             False              False   
3                  False             False              False   
4                  False             False              False   
...                  ...               ...                ...   
3328               

In [20]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [21]:
# same like df.isnull().sum()
df.isna().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [22]:
# methods to access column (one or many)
# method1
df['State']

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [23]:
type(df['State'])

pandas.core.series.Series

In [24]:
# method2 # problem is if column name having space it will throw error
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [25]:
# example of method2  error (column has space)
df.Account length

SyntaxError: invalid syntax (1891836818.py, line 2)

In [26]:
df['Total intl minutes']

0       10.0
1       13.7
2       12.2
3        6.6
4       10.1
        ... 
3328     9.9
3329     9.6
3330    14.1
3331     5.0
3332    13.7
Name: Total intl minutes, Length: 3333, dtype: float64

In [27]:
# select multiple columns : using column names
df[['Total intl minutes','State','Area code']]

Total intl minutes State  Area code
0                   10.0    KS        415
1                   13.7    OH        415
2                   12.2    NJ        415
3                    6.6    OH        408
4                   10.1    OK        415
...                  ...   ...        ...
3328                 9.9    AZ        415
3329                 9.6    WV        415
3330                14.1    RI        510
3331                 5.0    CT        510
3332                13.7    TN        415

[3333 rows x 3 columns]

In [28]:
df[['Total intl minutes','State','Area code']].head(2)

Total intl minutes State  Area code
0                10.0    KS        415
1                13.7    OH        415

In [29]:
# describe(): it gives statistical information from data , it ony load numerical columns
df.describe()

Account length    Area code  Number vmail messages  Total day minutes  \
count     3333.000000  3333.000000            3333.000000        3333.000000   
mean       101.064806   437.182418               8.099010         179.775098   
std         39.822106    42.371290              13.688365          54.467389   
min          1.000000   408.000000               0.000000           0.000000   
25%         74.000000   408.000000               0.000000         143.700000   
50%        101.000000   415.000000               0.000000         179.400000   
75%        127.000000   510.000000              20.000000         216.400000   
max        243.000000   510.000000              51.000000         350.800000   

       Total day calls  Total day charge  Total eve minutes  Total eve calls  \
count      3333.000000       3333.000000        3333.000000      3333.000000   
mean        100.435644         30.562307         200.980348       100.114311   
std          20.069084          9.259435          50.713844        19.922625   
min           0.000000          0.000000           0.000000         0.000000   
25%          87.000000         24.430000         166.600000        87.000000   
50%         101.000000         30.500000         201.400000       100.000000   
75%         114.000000         36.790000         235.300000       114.000000   
max         165.000000         59.640000         363.700000       170.000000   

       Total eve charge  Total night minutes  Total night calls  \
count       3333.000000          3333.000000        3333.000000   
mean          17.083540           200.872037         100.107711   
std            4.310668            50.573847          19.568609   
min            0.000000            23.200000          33.000000   
25%           14.160000           167.000000          87.000000   
50%           17.120000           201.200000         100.000000   
75%           20.000000           235.300000         113.000000   
max           30.910000           395.000000         175.000000   

       Total night charge  Total intl minutes  Total intl calls  \
count         3333.000000         3333.000000       3333.000000   
mean             9.039325           10.237294          4.479448   
std              2.275873            2.791840          2.461214   
min              1.040000            0.000000          0.000000   
25%              7.520000            8.500000          3.000000   
50%              9.050000           10.300000          4.000000   
75%             10.590000           12.100000          6.000000   
max             17.770000           20.000000         20.000000   

       Total intl charge  Customer service calls  
count        3333.000000             3333.000000  
mean            2.764581                1.562856  
std             0.753773                1.315491  
min             0.000000                0.000000  
25%             2.300000                1.000000  
50%             2.780000                1.000000  
75%             3.270000                2.000000  
max             5.400000                9.000000

In [30]:
df.describe(include='O') ## categorical variable (O- object data type)

State International plan Voice mail plan
count   3333               3333            3333
unique    51                  2               2
top       WV                 No              No
freq     106               3010            2411

In [33]:
# accessing rows using row_index
# df.iloc[n] : nth row 
df.iloc[1]

State                        OH
Account length              107
Area code                   415
International plan           No
Voice mail plan             Yes
Number vmail messages        26
Total day minutes         161.6
Total day calls             123
Total day charge          27.47
Total eve minutes         195.5
Total eve calls             103
Total eve charge          16.62
Total night minutes       254.4
Total night calls           103
Total night charge        11.45
Total intl minutes         13.7
Total intl calls              3
Total intl charge           3.7
Customer service calls        1
Churn                     False
Name: 1, dtype: object

In [32]:
# accessing rows using row_index
# df.iloc[n] : nth row 
df.iloc[1]

State                        OH
Account length              107
Area code                   415
International plan           No
Voice mail plan             Yes
Number vmail messages        26
Total day minutes         161.6
Total day calls             123
Total day charge          27.47
Total eve minutes         195.5
Total eve calls             103
Total eve charge          16.62
Total night minutes       254.4
Total night calls           103
Total night charge        11.45
Total intl minutes         13.7
Total intl calls              3
Total intl charge           3.7
Customer service calls        1
Churn                     False
Name: 1, dtype: object

In [34]:
## subsetting dataframe using iloc : iloc[n1:n2,m1:m2], n1,n2 : row,m1,m2: columns
df.iloc[2:5]  ## here i havenot given coma and columns so all columns i got

State  Account length  Area code International plan Voice mail plan  \
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
2                       0  False  
3                       2  False  
4                       3  False

In [36]:
df.iloc[1:4,0:5] # here i got 3 rows and 5 columns

State  Account length  Area code International plan Voice mail plan
1    OH             107        415                 No             Yes
2    NJ             137        415                 No              No
3    OH              84        408                Yes              No

In [37]:
# subseting the data using loc: provide row index and column names
df.loc[2:5,['State','Area code']]

State  Area code
2    NJ        415
3    OH        408
4    OK        415
5    AL        510

In [38]:
# sort_values : sort the dataframe by column name
df.sort_values(by = 'State') # by default ascending order

State  Account length  Area code International plan Voice mail plan  \
181     AK             126        415                 No              No   
550     AK             111        415                 No              No   
2929    AK              71        510                 No              No   
1260    AK              76        415                 No             Yes   
1803    AK             101        510                 No              No   
...    ...             ...        ...                ...             ...   
3258    WY             148        408                 No              No   
1265    WY              95        415                 No             Yes   
762     WY             161        415                Yes              No   
1628    WY             131        510                 No              No   
609     WY             111        415                 No              No   

      Number vmail messages  Total day minutes  Total day calls  \
181                       0               58.2               94   
550                       0              172.8               58   
2929                      0              185.0               84   
1260                     22              160.1              107   
1803                      0              174.9              105   
...                     ...                ...              ...   
3258                      0              243.0              115   
1265                     39              260.8              130   
762                       0              189.6               78   
1628                      0              110.9               74   
609                       0              146.2               55   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
181               9.89              138.7              118             11.79   
550              29.38              183.1              108             15.56   
2929             31.45              232.5              129             19.76   
1260             27.22              168.7              136             14.34   
1803             29.73              262.0               75             22.27   
...                ...                ...              ...               ...   
3258             41.31              191.8               91             16.30   
1265             44.34              213.4              111             18.14   
762              32.23              267.4              117             22.73   
1628             18.85              115.6               90              9.83   
609              24.85              261.5               83             22.23   

      Total night minutes  Total night calls  Total night charge  \
181                 136.8                 91                6.16   
550                 158.8                104                7.15   
2929                191.1                 82                8.60   
1260                 23.2                102                1.04   
1803                210.0                 93                9.45   
...                   ...                ...                 ...   
3258                117.8                 93                5.30   
1265                195.6                 97                8.80   
762                 184.5                137                8.30   
1628                190.5                114                8.57   
609                 163.2                116                7.34   

      Total intl minutes  Total intl calls  Total intl charge  \
181                 11.9                 1               3.21   
550                  7.9                 3               2.13   
2929                14.9                 4               4.02   
1260                 9.5                 4               2.57   
1803                 8.5                 5               2.30   
...                  ...               ...                ...   
3258                13.4                 5            

In [39]:
df.sort_values(by = 'State').head(2)

State  Account length  Area code International plan Voice mail plan  \
181    AK             126        415                 No              No   
550    AK             111        415                 No              No   

     Number vmail messages  Total day minutes  Total day calls  \
181                      0               58.2               94   
550                      0              172.8               58   

     Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
181              9.89              138.7              118             11.79   
550             29.38              183.1              108             15.56   

     Total night minutes  Total night calls  Total night charge  \
181                136.8                 91                6.16   
550                158.8                104                7.15   

     Total intl minutes  Total intl calls  Total intl charge  \
181                11.9                 1               3.21   
550                 7.9                 3               2.13   

     Customer service calls  Churn  
181                       5   True  
550                       4   True

In [40]:
df.sort_values(by = 'State',ascending=False)

State  Account length  Area code International plan Voice mail plan  \
273     WY             139        415                 No              No   
731     WY              90        415                 No              No   
2912    WY             151        415                 No              No   
1628    WY             131        510                 No              No   
2915    WY              58        510                 No              No   
...    ...             ...        ...                ...             ...   
1094    AK             115        415                 No              No   
3283    AK              99        510                 No              No   
1162    AK             173        510                 No              No   
2752    AK              55        408                 No             Yes   
2270    AK             146        415                 No              No   

      Number vmail messages  Total day minutes  Total day calls  \
273                       0              192.8              104   
731                       0              207.2              121   
2912                      0              170.2               89   
1628                      0              110.9               74   
2915                      0              210.1              126   
...                     ...                ...              ...   
1094                      0              245.2              105   
3283                      0              238.4               96   
1162                      0              172.5               78   
2752                     39              139.3              101   
2270                      0              195.9               86   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
273              32.78              234.4               96             19.92   
731              35.22              292.5              104             24.86   
2912             28.93              187.5               83             15.94   
1628             18.85              115.6               90              9.83   
2915             35.72              248.9              108             21.16   
...                ...                ...              ...               ...   
1094             41.68              159.0              109             13.52   
3283             40.53              246.5              130             20.95   
1162             29.33              142.6               91             12.12   
2752             23.68              178.3              117             15.16   
2270             33.30              228.6               82             19.43   

      Total night minutes  Total night calls  Total night charge  \
273                 203.2                101                9.14   
731                 226.3                103               10.18   
2912                119.5                100                5.38   
1628                190.5                114                8.57   
2915                158.6                 88                7.14   
...                   ...                ...                 ...   
1094                229.9                 74               10.35   
3283                198.4                117                8.93   
1162                102.0                 63                4.59   
2752                246.5                104               11.09   
2270                303.5                 94               13.66   

      Total intl minutes  Total intl calls  Total intl charge  \
273                 13.0                 3               3.51   
731                  8.0                 1               2.16   
2912                 4.3                 3               1.16   
1628                15.8                 9               4.27   
2915                14.4                 2               3.89   
...                  ...               ...                ...   
1094                 7.2                 8            

In [43]:
# sorting based on multiple column names
df.sort_values(by = ['State','Account length'])

State  Account length  Area code International plan Voice mail plan  \
2475    AK               1        408                 No              No   
36      AK              36        408                 No             Yes   
505     AK              41        415                 No              No   
282     AK              48        415                 No             Yes   
1054    AK              50        408                 No              No   
...    ...             ...        ...                ...             ...   
668     WY             171        415                 No              No   
2439    WY             177        415                 No              No   
1064    WY             185        415                Yes             Yes   
238     WY             215        510                 No              No   
1751    WY             225        415                 No              No   

      Number vmail messages  Total day minutes  Total day calls  \
2475                      0              175.2               74   
36                       30              146.3              128   
505                       0              159.3               66   
282                      37              211.7              115   
1054                      0              183.6              107   
...                     ...                ...              ...   
668                       0              231.2              135   
2439                      0              175.7              120   
1064                     30              154.1              114   
238                       0               83.6              148   
1751                      0              182.7              142   

      Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
2475             29.78              151.7               79             12.89   
36               24.87              162.5               80             13.81   
505              27.08              125.9               75             10.70   
282              35.99              159.9               84             13.59   
1054             31.21               58.6              118              4.98   
...                ...                ...              ...               ...   
668              39.30              188.7               74             16.04   
2439             29.87              168.6               90             14.33   
1064             26.20              118.7              106             10.09   
238              14.21              120.9               91             10.28   
1751             31.06              246.5               63             20.95   

      Total night minutes  Total night calls  Total night charge  \
2475                230.5                109               10.37   
36                  129.3                109                5.82   
505                 261.9                 76               11.79   
282                 144.1                 80                6.48   
1054                202.6                 99                9.12   
...                   ...                ...                 ...   
668                 206.9                124                9.31   
2439                198.9                110                8.95   
1064                258.4                105               11.63   
238                 226.6                110               10.20   
1751                218.0                103                9.81   

      Total intl minutes  Total intl calls  Total intl charge  \
2475                 5.3                 3               1.43   
36                  14.5                 6               3.92   
505                 11.1                 5               3.00   
282                 12.2                 1               3.29   
1054                 8.7                 3               2.35   
...                  ...               ...                ...   
668                 12.3                 1            

In [45]:
# indesing is same in data frame , if you wn reset the index , first copy the data frame and try
df_copy = df.sort_values(by = 'State').copy
df_copy

<bound method NDFrame.copy of      State  Account length  Area code International plan Voice mail plan  \
181     AK             126        415                 No              No   
550     AK             111        415                 No              No   
2929    AK              71        510                 No              No   
1260    AK              76        415                 No             Yes   
1803    AK             101        510                 No              No   
...    ...             ...        ...                ...             ...   
3258    WY             148        408                 No              No   
1265    WY              95        415                 No             Yes   
762     WY             161        415                Yes              No   
1628    WY             131        510                 No              No   
609     WY             111        415                 No              No   

      Number vmail messages  Total day minutes  Total day

In [47]:
df_copy.reset_index()

AttributeError: 'function' object has no attribute 'reset_index'

In [48]:
# use apply,;ambda expression to add chage in particular column
df.head()

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False

In [49]:
df['Area code new'] = df['Area code'].apply(lambda x : x+1000)
df


State  Account length  Area code International plan Voice mail plan  \
0       KS             128        415                 No             Yes   
1       OH             107        415                 No             Yes   
2       NJ             137        415                 No              No   
3       OH              84        408                Yes              No   
4       OK              75        415                Yes              No   
...    ...             ...        ...                ...             ...   
3328    AZ             192        415                 No             Yes   
3329    WV              68        415                 No              No   
3330    RI              28        510                 No              No   
3331    CT             184        510                Yes              No   
3332    TN              74        415                 No             Yes   

      Number vmail messages  Total day minutes  Total day calls  \
0                        25              265.1              110   
1                        26              161.6              123   
2                         0              243.4              114   
3                         0              299.4               71   
4                         0              166.7              113   
...                     ...                ...              ...   
3328                     36              156.2               77   
3329                      0              231.1               57   
3330                      0              180.8              109   
3331                      0              213.8              105   
3332                     25              234.4              113   

      Total day charge  Total eve minutes  ...  Total eve charge  \
0                45.07              197.4  ...             16.78   
1                27.47              195.5  ...             16.62   
2                41.38              121.2  ...             10.30   
3                50.90               61.9  ...              5.26   
4                28.34              148.3  ...             12.61   
...                ...                ...  ...               ...   
3328             26.55              215.5  ...             18.32   
3329             39.29              153.4  ...             13.04   
3330             30.74              288.8  ...             24.55   
3331             36.35              159.6  ...             13.57   
3332             39.85              265.9  ...             22.60   

      Total night minutes  Total night calls  Total night charge  \
0                   244.7                 91               11.01   
1                   254.4                103               11.45   
2                   162.6                104                7.32   
3                   196.9                 89                8.86   
4                   186.9                121                8.41   
...                   ...                ...                 ...   
3328                279.1                 83               12.56   
3329                191.3                123                8.61   
3330                191.9                 91                8.64   
3331                139.2                137                6.26   
3332                241.4                 77               10.86   

      Total intl minutes  Total intl calls  Total intl charge  \
0                   10.0                 3               2.70   
1                   13.7                 3               3.70   
2                   12.2                 5               3.29   
3                    6.6                 7               1.78   
4                   10.1                 3               2.73   
...                  ...               ...                ...   
3328                 9.9                 6               2.67   
3329                 9.6                 4               2.59   
3330                14.1                 6               3.81   
333

In [50]:
# value_counts : count of values present in particular column(categorical)
df['Churn'].value_counts()

Churn
False    2850
True      483
Name: count, dtype: int64

In [51]:
# filtering data based on conditions
# df[df[column name] <conditional operator> value]
df[df['Churn'] == True]

State  Account length  Area code International plan Voice mail plan  \
10      IN              65        415                 No              No   
15      NY             161        415                 No              No   
21      CO              77        408                 No              No   
33      AZ              12        408                 No              No   
41      MD             135        408                Yes             Yes   
...    ...             ...        ...                ...             ...   
3301    CA              84        415                 No              No   
3304    IL              71        510                Yes              No   
3320    GA             122        510                Yes              No   
3322    MD              62        408                 No              No   
3323    IN             117        415                 No              No   

      Number vmail messages  Total day minutes  Total day calls  \
10                        0              129.1              137   
15                        0              332.9               67   
21                        0               62.4               89   
33                        0              249.6              118   
41                       41              173.1               85   
...                     ...                ...              ...   
3301                      0              280.0              113   
3304                      0              186.1              114   
3320                      0              140.0              101   
3322                      0              321.1              105   
3323                      0              118.4              126   

      Total day charge  Total eve minutes  ...  Total eve charge  \
10               21.95              228.5  ...             19.42   
15               56.59              317.8  ...             27.01   
21               10.61              169.9  ...             14.44   
33               42.43              252.4  ...             21.45   
41               29.43              203.9  ...             17.33   
...                ...                ...  ...               ...   
3301             47.60              202.2  ...             17.19   
3304             31.64              198.6  ...             16.88   
3320             23.80              196.4  ...             16.69   
3322             54.59              265.5  ...             22.57   
3323             20.13              249.3  ...             21.19   

      Total night minutes  Total night calls  Total night charge  \
10                  208.8                111                9.40   
15                  160.6                128                7.23   
21                  209.6                 64                9.43   
33                  280.2                 90               12.61   
41                  122.2                 78                5.50   
...                   ...                ...                 ...   
3301                156.8                103                7.06   
3304                206.5                 80                9.29   
3320                120.1                133                5.40   
3322                180.5                 72                8.12   
3323                227.0                 56               10.22   

      Total intl minutes  Total intl calls  Total intl charge  \
10                  12.7                 6               3.43   
15                   5.4                 9               1.46   
21                   5.7                 6               1.54   
33                  11.8                 3               3.19   
41                  14.6                15               3.94   
...                  ...               ...                ...   
3301                10.4                 4               2.81   
3304                13.8                 5               3.73   
3320                 9.7                 4               2.62   
332

In [54]:
## filtering based on multiple columns
df[(df['Churn']==True) & (df['Area code']==408)]

State  Account length  Area code International plan Voice mail plan  \
21      CO              77        408                 No              No   
33      AZ              12        408                 No              No   
41      MD             135        408                Yes             Yes   
57      CO             121        408                 No             Yes   
77      NY             144        408                 No              No   
...    ...             ...        ...                ...             ...   
3151    ME              56        408                 No              No   
3205    MS             111        408                 No              No   
3246    NC              77        408                Yes             Yes   
3280    AR              76        408                 No              No   
3322    MD              62        408                 No              No   

      Number vmail messages  Total day minutes  Total day calls  \
21                        0               62.4               89   
33                        0              249.6              118   
41                       41              173.1               85   
57                       30              198.4              129   
77                        0               61.6              117   
...                     ...                ...              ...   
3151                      0              221.9              112   
3205                      0              294.7               90   
3246                     44              103.2              117   
3280                      0              107.3              140   
3322                      0              321.1              105   

      Total day charge  Total eve minutes  ...  Total eve charge  \
21               10.61              169.9  ...             14.44   
33               42.43              252.4  ...             21.45   
41               29.43              203.9  ...             17.33   
57               33.73               75.3  ...              6.40   
77               10.47               77.1  ...              6.55   
...                ...                ...  ...               ...   
3151             37.72              278.2  ...             23.65   
3205             50.10              294.6  ...             25.04   
3246             17.54              236.3  ...             20.09   
3280             18.24              238.2  ...             20.25   
3322             54.59              265.5  ...             22.57   

      Total night minutes  Total night calls  Total night charge  \
21                  209.6                 64                9.43   
33                  280.2                 90               12.61   
41                  122.2                 78                5.50   
57                  181.2                 77                8.15   
77                  173.0                 99                7.79   
...                   ...                ...                 ...   
3151                288.1                 85               12.96   
3205                260.1                121               11.70   
3246                203.5                101                9.16   
3280                271.8                116               12.23   
3322                180.5                 72                8.12   

      Total intl minutes  Total intl calls  Total intl charge  \
21                   5.7                 6               1.54   
33                  11.8                 3               3.19   
41                  14.6                15               3.94   
57                   5.8                 3               1.57   
77                   8.2                 7               2.21   
...                  ...               ...                ...   
3151                 7.1                 5               1.92   
3205                10.8                 3               2.92   
3246                11.9                 2               3.21   
328